### ISSUE TITLE
About supplementary 

### ISSUE THREAD

**Issue by zhao-yiqun** [Gorilla-Lab-SCUT/HelixSurf#1]
Hi, 

Thanks for your amazing work. There are some details and results you mentioned in paper are located in  supplementary,  but I can not find the supplementary from Arxiv, could you please upload the supplementary? Thanks!

Bests.

**Comment by lzhnb** [comment]
Hi,

Thanks for your attention! We have submitted a version with supplementary material to arxiv, and it will be updated soon, please be patient.
