### ISSUE TITLE
About the preprocess of the gt mesh

### ISSUE THREAD

**Issue by DavidXu-JJ** [Gorilla-Lab-SCUT/HelixSurf#4]
Hi, Thanks for your nice work.  Recently I'm trying to follow your paper.
I'm curious and a little confused about the preprocessing of the gt_mesh.(Like `0616_00_manhattansdf.obj`)
In README you described that we could refer to Manhattan-SDF to generate data. However, I didn't find any preprocess script with suffix `manhattansdf.obj` in both Manhattan-SDF and HelixSurf.
And the gt mesh data from Manhattan-SDF is not perfectly same as in HelixSurf data, as we can see from the following image.
<img width="841" alt="image" src="https://github.com/Gorilla-Lab-SCUT/HelixSurf/assets/68705456/cee929b6-d730-4a3f-a5f0-f7eba90c8ccf">
Could you please give me a hint about how to generate `0616_00_manhattansdf.obj` with gt mesh downloaded from Manhattan-SDF? Thank you for your time.
Best,
Jingwei Xu

**Comment by DavidXu-JJ** [comment]
My problem is already solved through some hacking tricks. So I will close the issue. But I'm still curious about how do you get the rotation matrix to align the floor and the wall of the scene to the xyz axis. I'm grateful if you can tell me some details about this.

**Comment by feiqiu-cyber** [comment]
> My problem is already solved through some hacking tricks. So I will close the issue. But I'm still curious about how do you get the rotation matrix to align the floor and the wall of the scene to the xyz axis. I'm grateful if you can tell me some details about this.

I am sorry to bother you, could you provide some info about how to produce the gt_mesh(like 0616_00_manhattansdf.obj)? Appreciate!

**Comment by DavidXu-JJ** [comment]
That's part of Scannet dataset, look for its dataset paper if you're interested.
